### ISSUE TITLE
error: A hook (`machines`) failed to load!

### ISSUE THREAD

**Issue by sudostack** [treelinehq/treeline#8]
Cannot `preview` Treeline project locally. Receiving error when doing the following:

I have an existing project on Treeline that I created a week back and it worked okay on a previous machine. I'm attempting to `preview` the project on a different machine and did the following...

`$ npm install -g treeline`

I created a directory for the project and changed directories, subsequently running:

`$ treeline preview`

I followed the instructions on screen and received the following:

`error: A hook (`machines`) failed to load!`
`An error occurred while communicating with the Treeline mothership: Could not install dependencies.`

It asks me to try the command with `sudo` which also did not work.

**Comment by sgress454** [comment]
My guess is that there is an error trying to download or compile one of your app's dependencies on the new machine.  Try:

```
sails_log__level=silly treeline preview
```

to get more output from the npm install command and see what errors it's throwing.  Post them back here and we'll get it figured out!

**Comment by sudostack** [comment]
@sgress454 thanks for that. Bad dependency. I removed it and worked like a charm. Thanks.
